import builders.ContentBuilder
import constants.TghUris
import models.nodes.ImgNode
import requests.ContentRequest
import requests.CreatePageRequest

val accessToken = "d3b25feccb89e508a9114afb82aa421fe2a9712b963b387cc5ad71e58722"

suspend fun main() {
    val telegraph = Telegraph()

    val builder = ContentBuilder()
//    builder.addParagraph("Lorem apsum bla aboba mogus")
//    builder.addImage("https://telegra.ph/file/0c44063aef409194f3cb0.jpg")
//    builder.addParagraph("Text after paragraph")

    val newPage = CreatePageRequest(
        accessToken = accessToken,
        "My first autogenerated article",
        "sparrow",
        "",
        builder.buildRequest(),
        true
    )
    val page = telegraph.createPage(newPage)
    println(page.url)
}