import models.Account
import models.ImgNode
import requests.ContentRequest
import requests.CreatePageRequest

suspend fun main() {
    val account = Account(
        shortName = "sparrow",
        authorName = "Sparrow1488",
        authorUrl = "",
        accessToken = "d3b25feccb89e508a9114afb82aa421fe2a9712b963b387cc5ad71e58722",
        authUrl = ""
    )
    val telegraph = Telegraph()

    val newPage = CreatePageRequest(
        accessToken = account.accessToken,
        "My first autogenerated article",
        "sparrow",
        "",
        ContentRequest(
            listOf(
                ImgNode("https://sun9-east.userapi.com/sun9-35/s/v1/ig2/gt1cqTznj-rGEeeKTNTYet5nDYzl-DQqpYpjDo9wFwyFk8S2vGyuovHRoqQHXkpEoUOE6YEtYM6gALaQf7ITX-1J.jpg?size=850x1127&quality=96&type=album"),
                ImgNode("https://sun9-west.userapi.com/sun9-7/s/v1/ig2/mktXc7HtY7gEr_ne_4VrnGrtW3WuhIhTxAlHnta0Vdfn3vkkT93FNS3W9s5-xsKkMYsMdhlii_vqRo5UFWAyCkCL.jpg?size=720x1280&quality=96&type=album")
            )
        ),
        true
    )
    val page = telegraph.createPage(newPage)
    println(page)
}
