import constants.TghUris
import models.ImgNode
import requests.ContentRequest
import requests.CreatePageRequest

val accessToken = "d3b25feccb89e508a9114afb82aa421fe2a9712b963b387cc5ad71e58722"

suspend fun main() {
    val telegraph = Telegraph()

    val imageSrc = telegraph.uploadImage("C:\\Users\\ilyao\\Downloads\\01.jpg")
    val imageUri = TghUris.BASE_URI + imageSrc.src

    val newPage = CreatePageRequest(
        accessToken = accessToken,
        "My first autogenerated article",
        "sparrow",
        "",
        ContentRequest(
            listOf(
                ImgNode(imageUri)
            )
        ),
        true
    )
    val page = telegraph.createPage(newPage)
    println(page.url)
}